"""empty message

Revision ID: 2474457f585b
Revises: cb3fb4784cb9
Create Date: 2020-06-05 14:28:32.353988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2474457f585b'
down_revision = 'cb3fb4784cb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('seeking_description', sa.String(), nullable=False))
    op.drop_column('venues', 'seekint_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('seekint_description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('venues', 'seeking_description')
    # ### end Alembic commands ###
