"""empty message

Revision ID: b428e2efa493
Revises: fdd8569f89b3
Create Date: 2020-06-10 15:22:30.297710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b428e2efa493'
down_revision = 'fdd8569f89b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('past_shows_count', sa.Integer(), nullable=True))
    op.add_column('venues', sa.Column('upcoming_shows_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'upcoming_shows_count')
    op.drop_column('venues', 'past_shows_count')
    # ### end Alembic commands ###
