"""empty message

Revision ID: fdd8569f89b3
Revises: 2474457f585b
Create Date: 2020-06-05 15:48:06.870000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdd8569f89b3'
down_revision = '2474457f585b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('start_time', sa.String(), nullable=False))
    op.drop_column('shows', 'venue_name')
    op.drop_column('shows', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('shows', sa.Column('venue_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('shows', 'start_time')
    # ### end Alembic commands ###
